### ISSUE TITLE
Can't build/open razor page.

### ISSUE THREAD

**Issue by richardaubin** [radzenhq/radzen-blazor-studio#72] opened 2022-11-22 16:28 UTC
My app builds/runs fine in VS Studio 2022 and actually runs when clicking the Run button in blazor studio.

Upon opening my solution in blazor studio and selecting my razor file, studio starts building and then fails with the following in the output

Unable to load one or more of the requested types.
Method 'GetProductsAsync' in type 'JewelerEStore.Infrastructure.ProductFeeds.ProductFeedService' from assembly 'JewelerEStore.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'GetBySpecAsync' in type 'JewelerEStore.Infrastructure.Data.EfRepository`1' from assembly 'JewelerEStore.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Exception has been thrown by the target of an invocation.

![image](https://user-images.githubusercontent.com/37956997/203368349-a687c504-402d-46ef-982e-36786c110d9d.png)

**Comment by akorchev** [comment] 2022-11-22 16:38
Can you provide more info about the services and those methods? How are they used and or registerd?

**Comment by richardaubin** [comment] 2022-11-22 18:46
> Can you provide more info about the services and those methods? How are they used and or registerd?

The services are registered in program.cs using the static class below

```
namespace JewelerEStore.Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services)
    {
        InitializeDatabase(services);

        services.AddTransient<IProductFeedService, ProductFeedService>();

        return services;
    }

    private static void InitializeDatabase(IServiceCollection services)
    {
        var cnn = new SqliteConnection("Filename=:memory:");
        cnn.Open();

        services.AddDbContext<AppDbContext>(options =>
        {
            options.UseSqlite(cnn);
            //options.UseSqlServer(builder.Configuration.GetConnectionString("JewelerEStore"));
            options.EnableSensitiveDataLogging();
            options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
        });

        services.AddTransient(typeof(IRepository<>), typeof(EfRepository<>));
    }
}
```

They are used in a ProductFeedPage.razor.cs partial class
with the EfRepository being injected in a MetiatR event handler: public partial class ProductFeedPage

```
public partial class ProductFeedPage
{
    [Inject] public IScopedMediator Mediator { get; set; }

    public IEnumerable<ProductFeedModel> ProductFeeds { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var request = new GetAllProductFeedsRequest(true);
        var result = await Mediator.Send(request);

        if (result.IsSuccess)
        {
            ProductFeeds = result.Value;
        }
    }
}
```

**Comment by akorchev** [comment] 2022-11-23 07:26
> The services are registered in program.cs using the static class below

This is why it doesn't work. Can you also post the code in Program.cs that calls the`AddInfrastructure` extension method? 
We will try to add some support for such cases or introduce some escape hatch.

FWIW registering those services explicitly (without the extension method) should probably make Radzen Blazor Studio work.

**Comment by richardaubin** [comment] 2022-11-23 08:38
Nothing out of the ordinary...

```
using JewelerEStore.Infrastructure;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddInfrastructure();
```

..

**Comment by akorchev** [comment] 2022-11-23 08:53
Unfortunately I couldn't reproduce the issue in a similar setup that registered services . Is there any chance you can send us your app to info@radzen.com? We will use it only to reproduce the problem and delete everything afterwards.

**Comment by richardaubin** [comment] 2022-11-23 08:59
I will try a few other things before I make that decision.  For example, I will be starting from a fresh app and introducing dependencies one by one, up to a similar state as my app to see if I can find out if and where it breaks.

**Comment by richardaubin** [comment] 2022-11-23 09:31
Turns out it's not those specific classes where it's failing, but the actual mediatr request handler, which has the service and repository injected in the constructor.

So I guess when the handler is executed, it isn't receiving the concrete classes.

**Comment by akorchev** [comment] 2022-11-23 09:36
That's very odd indeed. Let me know if you decide to send us a reproduction!

**Comment by akorchev** [comment] 2022-11-23 09:40
> Turns out it's not those specific classes where it's failing, but the actual mediatr request handler, which has the service and repository interfaces injected in the constructor.

I missed that completely. What is Mediatr? Does it replace the default dependency injection implementation? I wonder if this would somehow help: https://github.com/radzenhq/radzen-blazor-studio/issues/32

**Comment by richardaubin** [comment] 2022-11-23 09:51
https://github.com/jbogard/MediatR

A fairly popular nuget package :) (almost 90 million downloads)

**Comment by akorchev** [comment] 2022-11-23 10:34
I have requested access for akorchev@gmail.com as there isn't a google account for info@radzen.com.

**Comment by akorchev** [comment] 2022-11-23 11:12
Got the project! I will need to fix a few references to local files but I think I am all set to troubleshoot.

**Comment by akorchev** [comment] 2022-11-24 16:12
Hi @richardaubin,

The latest version 1.0.4 should address the issue reported here.

**Comment by richardaubin** [comment] 2022-11-29 01:51
I just tried now, and it is throwing another error now:

![image](https://user-images.githubusercontent.com/37956997/204418777-9d72572f-2b9f-4025-9ab1-30bece5d2898.png)

**Comment by akorchev** [comment] 2022-11-29 06:02
Hi @richardaubin,

I don't seem to have this page in the version of the project you have sent me. Mine has two pages - ProductFeedPage and Index. Both seem to render with Radzen 1.0.4.

![image](https://user-images.githubusercontent.com/454726/204450870-753c59b1-d12e-4ff7-bd49-3f5993a14fe0.png)
![image](https://user-images.githubusercontent.com/454726/204451046-a18fdb07-5acc-407d-b63b-224b44490e4f.png)


Can you send it too?

**Comment by richardaubin** [comment] 2022-11-29 14:43
I've since added Identity to the project, so not sure what's going on.

I'm going to pass on this for now and will use it in my next project.

**Comment by akorchev** [comment] 2022-12-02 06:30
Fair enough. I am closing this issue for now.

**Closed by akorchev** 2022-12-02 06:30 UTC
