### ISSUE TITLE
A project is visible multiple times in the files tab...

### ISSUE THREAD

**Issue by fl0wm0ti0n** [radzenhq/radzen-blazor-studio#94] opened 2023-02-25 15:04 UTC
If i open a SLN from VS one of the projects is open 4 times... if i click one all get selected, as is would be one..
![image](https://user-images.githubusercontent.com/24993288/221364086-d6f12ca8-9970-4cd0-926c-7433270c6f24.png)
![image](https://user-images.githubusercontent.com/24993288/221364099-5f47e991-be33-447f-b496-f70d587c0fcf.png)

**Comment by fl0wm0ti0n** [comment] 2023-02-25 17:11
Also after opening a different Project, 3 of the other duplicates doesn't go away...

![image](https://user-images.githubusercontent.com/24993288/221370297-76492ab4-8a65-4de9-ab61-33de4804c9da.png)

**Comment by akorchev** [comment] 2023-02-25 17:48
Hi @fl0wm0ti0n,

Radzen Blazor Studio does not currently support MAUI projects. This is probably the reason why you experience these issues.

**Comment by fl0wm0ti0n** [comment] 2023-02-25 17:52
Hi thanks for Quick response! 
I understand but why I get this error also with a radzen studio generated project?

i mean i open a radzen project and i still see the other MAUI project 3 times, but just as text i cant open the tree, see last picture i posted ;)

**Comment by akorchev** [comment] 2023-02-25 17:54
This is strange indeed and I am not sure why it could happen. Does restarting Radzen Blazor Studio help?

**Comment by fl0wm0ti0n** [comment] 2023-02-25 17:56
i restarted it a few times :( 

is there a kind of refresh or reset button? 

when i have restarted my Computer i can say if that helped ;)

**Comment by akorchev** [comment] 2023-02-25 17:59
No, there is no reset button. This project seems to appear in all solutions for some reason. If you want to you can send the problematic project and the test one to info@radzen.com and we will see if we can reproduce the phantom project appearing everywhere.

**Comment by fl0wm0ti0n** [comment] 2023-02-25 18:04
its interesting, but it selfhealed.. now it works also with other projects again...

**Comment by akorchev** [comment] 2023-04-27 04:45
I am closing this issue since there is no new information. Feel free to open a new one in case the problem reappears.

**Closed by akorchev** 2023-04-27 04:45 UTC
