### ISSUE TITLE
Start other project if radzen project has asp.net core lib references

### ISSUE THREAD

**Issue by sergpy** [radzenhq/radzen-blazor-studio#75] opened 2022-11-25 09:17 UTC
My radzen project has few core Asp.Net libraries, 
but when the radzen project starts, one of the referenced projects is launched, but not the radzen project

**Comment by akorchev** [comment] 2022-11-25 09:20
This sounds as a duplicate of your other issue. Closing it.

**Closed by akorchev** 2022-11-25 09:20 UTC
