### ISSUE TITLE
Deleting a file does not remove it from the project explorer panel & file system

### ISSUE THREAD

**Issue by AnNormalie** [radzenhq/radzen-blazor-studio#9] opened 2022-03-29 18:01 UTC
Deleting a file eg a radzen .log file from the project explorer panel does not visibly remove it.
It also seems that the file isn't removed in the file system, but the content was removed

When selecting a deleted file it shows an json formatted error in the code section.
```json
{
    "error": "System.IO.FileNotFoundException: Could not find file 'C:\\Users\\User\\source\\repos\\{SomeName}\\BlazorTestProject\\server\\radzen_20220202171940_12128.log'.\r\nFile name: 'C:\\Users\\User\\source\\repos\\{SomeName}\\BlazorTestProject\\server\\radzen_20220202171940_12128.log'\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\r\n   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)\r\n   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)\r\n   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)\r\n   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)\r\n   at Radzen.Server.ProjectContext.OpenFileAsync(String filePath, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 359\r\n   at Radzen.Server.ProgramController.OpenFile(OpenFileRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 210\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
```

**Comment by AnNormalie** [comment] 2022-03-29 19:38
After updating to `1.0.0-preview.2` the file gets removed from the filesystem but is still visible in the project explorer panel. When I try to access it again, I get the same error as above.

**Comment by mdchafin** [comment] 2022-03-29 23:00
Try preview 3

**Comment by AnNormalie** [comment] 2022-03-30 06:17
Still getting this with `1.0.0-preview.3`

**Comment by akorchev** [comment] 2022-03-30 10:57
@AnNormalie Could you try [downloading](https://www.radzen.com/blazor-studio/download/) the latest version - 1.0.0.preview.4? We can't reproduce the original issue there so it may have been fixed.

**Comment by AnNormalie** [comment] 2022-03-30 11:19
@akorchev I have just created a file within RBS at project level called `SomeFile.cs` then I right clicked and deleted it.
As you can see in the screenshot, the file was removed from the file system but is still present in RBS.

When creating the file, I had a similar issue. The file was created and opend in the code editor, but wasnt shown in the project tree. After restarting RBS it was listed.

Let me know if I can help you further to analyse this issue.
![image](https://user-images.githubusercontent.com/86982835/160822809-61043880-2bac-4e58-b52f-ccc1bd2128cb.png)

**Comment by AnNormalie** [comment] 2022-03-30 12:07
Yes, just created the `SomePage.cs` file again and its not visible in the project tree.
![image](https://user-images.githubusercontent.com/86982835/160830858-fe040ed9-c83b-4ea3-861b-18a5e532414a.png)

**Comment by akorchev** [comment] 2022-03-30 12:10
We will keep trying to reproduce the problem. For some reason all file system change notifications seem to not fire in this case. Is there something special about the project location? Is it a mapped or network drive?

**Comment by mdchafin** [comment] 2022-03-30 12:10
Preview 4 is no better. I don’t think this was CTP release ready.

**Comment by mdchafin** [comment] 2022-03-30 12:14
Yes. I downloaded it this morning and tested it.

**Comment by akorchev** [comment] 2022-03-30 12:24
Thank you for your patience! Does it work after Radzen Blazor Studio has finished building the project? The message in the status bar should be "Ready". Can you also try creating a file outside of RBS and check if it appears? 

FWIW the issues described here seem to work as expected in our local tests.

 Creating a new file.
![new-file](https://user-images.githubusercontent.com/454726/160832840-f2f9dab9-99f7-4675-b2ea-90953662949d.gif)

Deleting a file.
![delete-file](https://user-images.githubusercontent.com/454726/160832940-b67e76ac-9d34-4e0a-ad00-82a73b517af8.gif)

Creating a new page.
![create-page](https://user-images.githubusercontent.com/454726/160833174-be3cf811-88ad-49e7-81ca-b8db441fc814.gif)

**Comment by AnNormalie** [comment] 2022-03-30 12:38
Yes, also still present when RBS is Ready. Just deleted `SomePage.cs`
![image](https://user-images.githubusercontent.com/86982835/160835870-c8a426b8-4b5b-495d-88e4-bc8ea81586d7.png)

**Comment by akorchev** [comment] 2022-03-30 12:46
Thank you for confirming this @AnNormalie. It looks as if FileSystemWatcher doesn't report any changes and I still fail to understand why. Would you be willing to try a new build which some additional logging added?

**Comment by akorchev** [comment] 2022-03-30 13:05
> @akorchev the project location is at local C:\ drive and looks like:
> 
> `C:\Git\{abc.def.ghi}\app.prj\{SomeProjectName}\server`

Something just occurred to me - does the actual project directory contain "obj" or "bin" somewhere in the full path?

**Comment by AnNormalie** [comment] 2022-03-30 13:27
yes it does
![image](https://user-images.githubusercontent.com/86982835/160845578-14a62cb6-11de-4719-9d8d-761819acd5a2.png)

**Comment by akorchev** [comment] 2022-03-30 13:35
I am sorry I meant any of the parent directories `C:\Git\{abc.def.ghi}\app.prj\{SomeProjectName}\`. Those `bin` and `obj` which are in the project itself are not the problem. RBS ignores any changes in bin and obj directories. However if your project is something like `c:\git\bin\app.prj\MyProject` it will ignore all changes.

**Comment by AnNormalie** [comment] 2022-03-30 13:44
@akorchev I wrote you an email to info@radzen.com including the full path.

bin or obj is not in the directory structure.

**Comment by AnNormalie** [comment] 2022-03-30 16:10
If I can help you any further, please let me know.

> Would you be willing to try a new build which some additional logging added?

no problem, just let me know.

**Comment by akorchev** [comment] 2022-03-30 17:02
Could you let me know what happens if you do the following:

1. Open your application
2. Wait for the status message (bottom right corner) to become 'Ready'.
3. Try to open an existing file.

Does the status message ever become 'Ready'? If yes - does the file open as expected or is there an exception again?

**Comment by AnNormalie** [comment] 2022-03-30 17:13
Just tried it also with a different project.
Yes status message becomes ready, didn't even notice that it switched and project is also running.
![image](https://user-images.githubusercontent.com/86982835/160892689-7ba2af82-02d9-47cb-a4a1-b277aec3edea.png)

Also when opening a page, the designer shows up.
![image](https://user-images.githubusercontent.com/86982835/160892967-3bf20559-7895-4962-b9ee-225543c95bed.png)

**Comment by akorchev** [comment] 2022-03-30 20:25
After further investigation there seems to be at least three different issues related the build not being finished.

1. If one tries to create a new page while the build is not finished there is a NullReferenceException.
2. If one tries to delete a file while there is a build in progress the file may remain in the tree until the build finishes.
3. In some cases the build never finishes and the status stays indefinitely as "Building" without any errors being reported.

We will try to address all three with tomorrow's release.

**Comment by akorchev** [comment] 2022-03-31 14:20
We release 1.0.0.preview5 which tries to resolve the above three issues:

1. Deleting a file should not leave items in the tree.
2. Creating a new page should not throw exceptions.

You can give it a try.

**Comment by AnNormalie** [comment] 2022-03-31 15:24
@akorchev still same beahviour with preview.5
Meanwhile I tested it at my PC at work with Windows 10 and with my private PC Windows 11 and also different projects.

- Creating a new file (eg. SomePage.cs) does create it, but doesn't show up in the tree (btw. after creation it also gets opened in the code editor).
- Deleting a file deletes it from the file explorer but is still present in the RBS project tree.
- Just saw on creating a page (with code-behind) the files show up in the project tree but an exception pop up:
```
Value cannot be null. (Parameter 'connectionString')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at IeMsWebApp.Startup.<ConfigureServices>b__6_2(DbContextOptionsBuilder options)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Radzen.Server.Router.OnRouteChanged(Object sender, RouteChangedEventArgs e) in /Users/korchev/github/radzen-next/Radzen.Server/Router.cs:line 56
   at Radzen.Server.RouterService.Route(Type component, Type defaultLayout) in /Users/korchev/github/radzen-next/Radzen.Server/RouterService.cs:line 19
   at Radzen.Server.CircuitHost.AddComponent(Type layout, Type page) in /Users/korchev/github/radzen-next/Radzen.Server/CircuitHost.cs:line 34
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 417
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 306
```
I have a `appsettings.json` and a `appsettings.development.json` the ConnectioStrings section for the db connection is only in the `appsettings.json`

- `appsettings.json` (this is what got generated by Radzen IDE and most values like connection string will be overridden by env variables when in production)
```json
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "ConnectionStrings": {
    "iemsdbConnection": "Server={server};Initial Catalog={dbname};Persist Security Info=False;User ID={user};Password={passw};MultipleActiveResultSets=True;Encrypt=false;TrustServerCertificate=true;Connection Timeout=30"
  },
  "AzureAD": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "SomeDomain.com",
    "TenantId": "xxx-xxx-xxx-xxx-xxx",
    "ClientId": "xxx-xxx-xxx-xxx-xxx",
    "ClientSecret": "SomeSecret",
    "CallbackPath": "/signin-oidc"
  }
}
```

- `appsettings.development.json` (this this is some additional connection that I need during dev and in production it will also be set by env vars)
```json
{
  "ConnectionStrings": {
    "AzureStorage": "{some connection string to Azure BlobStorage}"
  },
  
}
```

Let me know if I can provide you more information.

**Comment by akorchev** [comment] 2022-03-31 15:33
> Creating a new file (eg. SomePage.cs) does create it, but doesn't show up in the tree (btw. after creation it also gets opened in the code editor).
> Deleting a file deletes it from the file explorer but is still present in the RBS project tree.

I am really at a loss here. Does this work if you wait for the project build to finish (status message "Ready")? It probably won't but still worth a try.

It looks as if file system notifications (create file, delete file) aren't working at all. I will add some additional logging and prepare a special build for you. Will send a link to it over email.

**Comment by AnNormalie** [comment] 2022-03-31 15:35
> I am really at a loss here. Does this work if you wait for the project build to finish (status message "Ready")? It probably won't but still worth a try.

For all these tests the status message was `Ready`. Loading and building was done.

**Comment by akorchev** [comment] 2022-03-31 16:10
@AnNormalie I have sent you an email with a build which has verbose logging enabled. Fingers crossed it reveals the mystery.

**Comment by akorchev** [comment] 2022-04-01 17:31
We were finally able to reproduce the problem - adding new files and directories and deleting files at root level wasn't reflected at root level of the tree. Radzen Blazor Studio 1.0.0.preview.6 was just released and should address this problem.

The issue with the connection strings is different and we will need more investigation to reproduce it.

**Comment by AnNormalie** [comment] 2022-04-01 19:11
Amazing, could confirm with `1.0.0.preview.6` I could not reproduce the issue.

Shall I open a new Issue for the appsettings/connection string issue, it seems that it is not related to this one here?

**Comment by akorchev** [comment] 2022-04-02 07:52
> Amazing, could confirm with 1.0.0.preview.6 I could not reproduce the issue.
Happy to finally clear that out. Closing this issue now.

**Closed by akorchev** 2022-04-02 07:52 UTC
