### ISSUE TITLE
Build failed with preview.16 - must contain a non-null value when exiting constructor

### ISSUE THREAD

**Issue by AnNormalie** [radzenhq/radzen-blazor-studio#45] opened 2022-06-09 17:46 UTC
After updating to preview.16 the build is failing with the following issue:

`Msbuild failed when processing the file 'C:\Users\User\source\repos\abc\xyz.webapp\src\abc.Shared\abc.Shared.csproj' with message: C:\Users\User\source\repos\abc\xyzwebapp\src\abc.Shared\Dtos\SomeFolder\SomeDto.cs: (26, 46): Non-nullable property 'SomeProperty' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.`

This message gets spammed for every `string` and `ICollection` property.
With older versions the project built successfully.
With VisualStudio 2022 the project is running also.

This is a shared .net6 library project containing dto models of the api that gets called from the blazor project.
The models looks like:
```csharp
public class ArticleDto
{
    public int Id { get; set; }
    public string Number { get; set; }
    public string Name { get; set; }
    public string SomeProperty{ get; set; }
    public string Characteristics { get; set; }

    public ICollection<OrderDto> Orders { get; set; }
    public ICollection<SomethingOtherDto> SomeThingOthers { get; set; }

}
```

**Comment by akorchev** [comment] 2022-06-09 17:51
RBS now logs MSBuild errors as they often prevent loading the project. That's the major new change. It is basically running `dotnet build path_to_csproj`. Can you again send us your project so we can investigate further?

**Comment by akorchev** [comment] 2022-06-09 18:04
After reading [this](https://stackoverflow.com/questions/67505347/non-nullable-property-must-contain-a-non-null-value-when-exiting-constructor-co) I wonder if it is actually a warning that is misinterpreted as an error. Do you see such warnings in Visual Studio (as in the screenshot from the linked SO thread)?

**Comment by akorchev** [comment] 2022-06-09 18:14
I was able to reproduce the problem. Will investigate a solution.

**Comment by akorchev** [comment] 2022-06-09 18:35
I think I fixed that. A new release is baking.

**Comment by akorchev** [comment] 2022-06-09 19:08
Preview 17 should be out. It is supposed to get rid of this issue.

**Comment by AnNormalie** [comment] 2022-06-09 19:23
preview.17 builds the project successful.
Im just curious, could it be that it added an empty wwwroot folder in the shared project?
Could not remember that it was me that added it.

Pages that use direct db access are opening normally in designer mode.
But when I try to open a page that injects a API access service it stucks and no page could be opened until I restart RBS. The API is not running at the moment. Is this a problem?

**Comment by akorchev** [comment] 2022-06-10 14:30
> Im just curious, could it be that it added an empty wwwroot folder in the shared project?
It definitely is creating the empty wwwroot directory. This should not happen for class libraries and we will address that.
> injects a API access service it stucks and no page could be opened until I restart RBS.
What does the service do and how do you use it in the page?

**Comment by AnNormalie** [comment] 2022-06-10 19:47
It doesn't seem to be the service that does the API access, I have just tried it with a running API. 
When I clear all references on that page to the shared dll project, the designer is working again.

**Comment by akorchev** [comment] 2022-06-12 08:16
It still sounds as an issue we would have to address. What is the general idea of the service and how are you using it in the page? Probably we would be able to reproduce the exception.

**Comment by AnNormalie** [comment] 2022-06-12 20:12
The service allows me to simply perform actions with the API, basically CRUD operations similar to the one generated from Radzen.

I started to remove code in page *.razor and in code behind *.razor.cs to see what leads to this problem. The page isn't the issue, but when I remove the reference in the code behind file to the dtos of my shared library, the page gets rendered in RBS again. 

In the example of my code following below this must be removed:
```csharp
some.library.shared.Dtos.Language.LanguageDto _getLanguageByIdDto;
    protected some.library.shared.Dtos.Language.LanguageDto getLanguageByIdDto
    {
        get
        {
            return _getLanguageByIdDto;
        }
        set
        {
            if (!object.Equals(_getLanguageByIdDto, value))
            {
                var args = new PropertyChangedEventArgs() { Name = "getLanguageByIdDto", NewValue = value, OldValue = _getLanguageByIdDto };
                _getLanguageByIdDto = value;
                OnPropertyChanged(args);
                Reload();
            }
        }
    }
```

## Original code of Interface, implementation and page with code behind
Interface:
```csharp
using some.library.shared.Dtos.Language;
using System;
using System.Threading.Tasks;

namespace MyWebApp.Services.Interfaces;

public interface IMyRestApiService
{
    #region Language
    Task<PagedLanguageResultDto> GetLanguagesPaged(LanguageParametersDto queryParameters);
    Task<LanguageDto> GetLanguageById(int id, string[] includes = null);
    Task<LanguageDto> CreateLanguage(LanguageForCreationDto body);
    Task<bool> UpdateLanguage(int id, LanguageForUpdateDto body);
    Task<bool> DeleteLanguage(int id);
    #endregion Language
}
```

Implementation:
```csharp
using MyWebApp.Services.Interfaces;
using some.library.shared.Dtos.Language;
using Microsoft.Extensions.Configuration;
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web;

namespace MyWebApp.Services;

public class MyRestApiService : IMyRestApiService
{
    private readonly HttpClient httpClient;
    private readonly Uri baseUri;
    private readonly JsonSerializerOptions _options;

    public MyRestApiService(IConfiguration configuration)
    {
        this.httpClient = new HttpClient();
        this.baseUri = new Uri(configuration["MyRestApiBaseUri"]);
        _options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    }

    public async Task<LanguageDto> CreateLanguage(LanguageForCreationDto body)
    {
        var uri = new Uri(baseUri, $"api/Languages");

        var message = new HttpRequestMessage(HttpMethod.Post, uri);

        message.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, "application/json");

        var response = await httpClient.SendAsync(message);

        response.EnsureSuccessStatusCode();

        var content = await response.Content.ReadAsStringAsync();

        return JsonSerializer.Deserialize<LanguageDto>(content, _options);

    }

    public async Task<bool> DeleteLanguage(int id)
    {
        var uri = new Uri(baseUri, $"api/Language/{id}");

        var message = new HttpRequestMessage(HttpMethod.Delete, uri);

        var response = await httpClient.SendAsync(message);

        response.EnsureSuccessStatusCode();

        return true;
    }

    public async Task<PagedLanguageResultDto> GetLanguagesPaged(LanguageParametersDto queryParameters)
    {
        var uri = new Uri(baseUri, $"api/Languages");

        var uriBuilder = new UriBuilder(uri);
        var queryString = HttpUtility.ParseQueryString(uriBuilder.Query);

        if (queryParameters.Filters != null)
            queryString.Add("Filters", $"{queryParameters.Filters}");
        if (queryParameters.SortOrder != null)
            queryString.Add("SortOrder", $"{queryParameters.SortOrder}");
        if (queryParameters.Includes != null)
            queryString.Add("Includes", $"{string.Join(",", queryParameters.Includes)}");
        queryString.Add("PageNumber", $"{queryParameters.PageNumber}");
        queryString.Add("PageSize", $"{queryParameters.PageSize}");

        uriBuilder.Query = queryString.ToString();
        uri = uriBuilder.Uri;

        var message = new HttpRequestMessage(HttpMethod.Get, uri);

        var response = await httpClient.SendAsync(message);

        response.EnsureSuccessStatusCode();

        var content = await response.Content.ReadAsStringAsync();

        return JsonSerializer.Deserialize<PagedLanguageResultDto>(content, _options);

    }

    public async Task<LanguageDto> GetLanguageById(int id, string[] includes = null)
    {
        var uri = new Uri(baseUri, $"api/Languages/{id}");

        var uriBuilder = new UriBuilder(uri);
        var queryString = HttpUtility.ParseQueryString(uriBuilder.Query);

        if (includes != null)
            queryString.Add("Includes", $"{string.Join(",", includes)}");

        uriBuilder.Query = queryString.ToString();
        uri = uriBuilder.Uri;

        var message = new HttpRequestMessage(HttpMethod.Get, uri);

        var response = await httpClient.SendAsync(message);

        response.EnsureSuccessStatusCode();

        var content = await response.Content.ReadAsStringAsync();

        return JsonSerializer.Deserialize<LanguageDto>(content, _options);
    }

    public async Task<bool> UpdateLanguage(int id, LanguageForUpdateDto body)
    {
        var uri = new Uri(baseUri, $"api/Languages/{id}");

        var message = new HttpRequestMessage(HttpMethod.Put, uri);

        message.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, "application/json");

        var response = await httpClient.SendAsync(message);

        response.EnsureSuccessStatusCode();

        return true;
    }

}
``` 

Registration in `Startup.cs`
```csharp
services.AddScoped<IMyRestApiService, MyRestApiService>();
```

Page:
```
@page "/details-language-api/{Id}"
@layout MainLayout
@inherits MyWebApp.Pages.DetailsLanguageApiComponent

@using Radzen
@using Radzen.Blazor
@using Microsoft.AspNetCore.Authorization

@attribute [Authorize(Roles = "Admin")]

<PageTitle>Details Language Api</PageTitle>

<RadzenContent Container="main">
  <ChildContent>
    <RadzenHeading Size="H1" Text="Details Language Api">
    </RadzenHeading>
    <div class="row">
        <div class="col-md-12" style="">
            <RadzenButton Text="Back" Icon="undo" ButtonStyle="Radzen.ButtonStyle.Info" Style="" Click="@ButtonBackClick"></RadzenButton>          
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
          <RadzenTabs>
              <Tabs>
                  <RadzenTabsItem Text="Details">
                      <div class="row">
                        <div class="col-md-12">
                            <RadzenCard>
                                <RadzenTextBox Style="width: 100%" Value="Some text in here"></RadzenTextBox>
                            </RadzenCard>                       
                        </div>
                      </div>  
                  </RadzenTabsItem>
              </Tabs>
          </RadzenTabs>       
      </div>
    </div>
  </ChildContent>
</RadzenContent>

```

Code behind:
```csharp
using MyWebApp.Services.Interfaces;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.JSInterop;
using Radzen;
using Radzen.Blazor;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyWebApp.Pages;

public partial class DetailsLanguageApiComponent : ComponentBase
{
    [Parameter(CaptureUnmatchedValues = true)]
    public IReadOnlyDictionary<string, dynamic> Attributes { get; set; }

    public void Reload()
    {
        InvokeAsync(StateHasChanged); 
    }

    public void OnPropertyChanged(PropertyChangedEventArgs args)
    {
    }

    [Inject]
    protected IJSRuntime JSRuntime { get; set; }

    [Inject]
    protected NavigationManager UriHelper { get; set; }

    [Inject]
    protected DialogService DialogService { get; set; }

    [Inject]
    protected TooltipService TooltipService { get; set; }

    [Inject]
    protected ContextMenuService ContextMenuService { get; set; }

    [Inject]
    protected NotificationService NotificationService { get; set; }

    [Inject]
    protected SecurityService Security { get; set; }

    [Inject]
    protected AuthenticationStateProvider AuthenticationStateProvider { get; set; }

    [Inject]
    protected IMyRestApiService MyRestApiService { get; set; }

    [Parameter]
    public dynamic Id { get; set; }

    protected bool isLoading;

    some.library.shared.Dtos.Language.LanguageDto _getLanguageByIdDto;
    protected some.library.shared.Dtos.Language.LanguageDto getLanguageByIdDto
    {
        get
        {
            return _getLanguageByIdDto;
        }
        set
        {
            if (!object.Equals(_getLanguageByIdDto, value))
            {
                var args = new PropertyChangedEventArgs() { Name = "getLanguageByIdDto", NewValue = value, OldValue = _getLanguageByIdDto };
                _getLanguageByIdDto = value;
                OnPropertyChanged(args);
                Reload();
            }
        }
    }



    protected override async Task OnInitializedAsync()
    {
        await Security.InitializeAsync(AuthenticationStateProvider);
        if (!Security.IsAuthenticated())
        {
            UriHelper.NavigateTo("Login", true);
        }
        else
        {
            await Load();
        }
    }

    protected async Task Load()
    {
        isLoading = true;

        try
        {
            var includes = new string[]
            {
                "someIncludes"
            };

            var result = await MyRestApiService.GetLanguageById(Convert.ChangeType(Id, Type.GetTypeCode(typeof(int))), includes);
            getLanguageByIdDto = result;

        }
        catch (System.Exception someUpdateLanguageException)
        {
            NotificationService.Notify(
                new NotificationMessage()
                {
                    Severity = NotificationSeverity.Error,
                    Summary = $"Error",
                    Detail = $"Unable to update Language"
                });
        }
        finally
        {
            isLoading = false;
        }

    }

    protected async Task ButtonBackClick(MouseEventArgs args)
    {
        UriHelper.NavigateTo("language-api");
    }
}

```

I hope this helps you. If you need more information, please let me know.

**Comment by akorchev** [comment] 2022-06-16 07:38
Unfortunately this doesn't help a lot. It seems that the code in OnInitializeAsync is running although RBS tries not to. I am afraid we would need some sort of replication.

**Comment by AnNormalie** [comment] 2022-06-17 17:40
I have setup a sample project with an API to reproduce the issue.
https://github.com/AnNormalie/RbsSampleApp

It has and WebApi project `RbsSampleApi.csproj` where you need to run `update-database` before you run it.
It is using a local SqlExpress DB (see appsettings.json)
Server: `Server=(localdb)\\MSSQLLocalDB`
Initial Catalog: `Initial Catalog=RBS_SAMPLE_DB`
with Windows Authentication.
The WebApi runs on `https://localhost:5005/`

An Blazor Server Webapp `RbsSampleWebApp.csproj`, this is generated with Radzen and SQL data source. In addition you can see the `RbsSampleApiService.cs` Service which does the API access.

And a shared Library `RBSSample.Shared.csproj` which hold all DTOs used from the API and the WebApp.

By now I could not reproduce the exact issue, but I got a exception when accessing the `LanguagesApi.razor` page
With VisualStudio the project is running and I can View and Create Items in the `languages-api`  page.

Maybe if this error could get fixed I can continue with this project to reproduce the original issue.

```
Attempt by method 'RbsSampleWebApp.Pages.Language.LanguagesApi+<>c.<OnInitializedAsync>b__2_3(Int32)' to access method 'RBSSample.Shared.Dtos.Shared.BasePaginationParameters.set_DefaultPageSize(Int32)' failed.
   at RbsSampleWebApp.Pages.Language.LanguagesApi.<>c.<OnInitializedAsync>b__2_3(Int32 index)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToArray()
   at RbsSampleWebApp.Pages.Language.LanguagesApi.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Radzen.Server.Router.OnRouteChanged(Object sender, RouteChangedEventArgs e) in /Users/korchev/github/radzen-next/Radzen.Server/Router.cs:line 57
   at Radzen.Server.RouterService.Route(Type component, Type defaultLayout) in /Users/korchev/github/radzen-next/Radzen.Server/RouterService.cs:line 19
   at Radzen.Server.CircuitHost.AddComponent(Type layout, Type page) in /Users/korchev/github/radzen-next/Radzen.Server/CircuitHost.cs:line 34
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 411
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 325
```

**Comment by akorchev** [comment] 2022-06-20 14:24
This error should be fixed with the Alpha we released today (you will have to manually install it from [here](https://forum.radzen.com/t/radzen-blazor-studio-alpha-released/11102))

**Comment by AnNormalie** [comment] 2022-06-21 16:05
The error from the RbsSampleApp is fixed, but I didn't have time to continue to reproduce the original error.
In the original App I get now a different behaviour with alpha.1

I am getting this error when I try to access the page:
![image](https://user-images.githubusercontent.com/86982835/174845850-dd0be6b2-7905-4973-8032-916c9924fbf8.png)

And I am unable to open another page or file anymore after I opened the page that throws this error.

**Comment by akorchev** [comment] 2022-06-21 18:49
There is probably more info in the log file. It is accessible from the Help menu.

**Comment by AnNormalie** [comment] 2022-06-22 07:41
The logfile only has its checking for updates information listed.

I could not reproduce it with the SampleProject at the moment.
But I just found that if I remove the Collection properties from some of the DTOs then the designer is working again for this page.

eg: `public virtual ICollection<ParameterDto>? Parameters { get; set; }`

The production database of my app is way bigger, could it be some sort of reference loop handling, even if this properties doesn't get loaded and should be `null`?

I will try to continue to reproduce it with the SampleProject.

**Comment by akorchev** [comment] 2022-06-22 07:53
> The production database of my app is way bigger, could it be some sort of reference loop handling
This is probably what happens and the server goes in an endless loop. Hence the "failed to fetch" error and nothing being logged. Is there any recursive relationship between those DTO classes?

**Comment by akorchev** [comment] 2022-11-22 14:31
Closing due to inactivity. Feel free to comment if the problem persists with the latest version of Radzen Blazor Studio.

**Closed by akorchev** 2022-11-22 14:31 UTC
